### ISSUE TITLE
Plugin does not create tables in existing installation

### ISSUE THREAD

**Issue by R3v1L** [takezoe/gitbucket-gist-plugin#5]
Followed the installation instructions and put the jar file in the plugins directory. The plugin is loaded and I get a Snippets link near Gitbucket logo, but when I click on it I got the following:

org.h2.jdbc.JdbcSQLException: Table "GIST" not found; SQL statement: (THE SQL TO GET THE GISTs)

I suspect the problem is the plugin is not creating the tables at initialization. Maybe it's me that I forgot an step, but I don't remember any step to create tables in any db.

Could you check it or point me in the right direction please?

**Comment by takezoe** [comment]
Fixed in #7

**Comment by R3v1L** [comment]
Hi again Takezoe. Sorry for reopening, but the problem is not fixed.

I cloned the repo again and followed install instructions with a clean install but getting the same error. You can see it at gist gist:c2932c59974509efa5cf.

**Comment by hayasshi** [comment]
@R3v1L 
Hi.
You must be fixed your database.
* Administrator login on your GitBucket.
* Administration > H2 Console and connect to "jdbc:h2:~/.gitbucket/data".
* Run "DELETE FROM PLUGIN WHERE PLUGIN_ID='gist'"
* Restart GitBucket.

**Comment by R3v1L** [comment]
Hi Hayasshi.

The problem I have is that tables are not created. 

Alhought I executed the deletion statement but there is no table PLUGIN in the database.

When I realized I could execute the table creation manually, I inspected the schema using H2 Console and tried to execute the statements at gitbucket-gist-plugin/src/main/resources/update/1_0.sql

They fail because table ACCOUNT does not exist na d I get errors when creating foreign keys etc.

I modified them to include the tables inside the information schema and created them again, but same errors.

The tables are created, and when I try to use the plugin I get the same result that I posted to the gist.

**Comment by R3v1L** [comment]
I Just realized I tried to do that in the 

jdbc:h2:~/test

database.

When I use
jdbc:h2:~/.gitbucket/data

I can't login in it with H2 console. Is there any default password or something? My users password does not work.

**Comment by R3v1L** [comment]
Searching in other issues at gitbucket repo I found the console default user is sa, but I can't access the database with that user either.

Could you help me?

**Comment by hayasshi** [comment]
Default user and password is "sa".
Ref to https://github.com/takezoe/gitbucket/blob/master/src/main/resources/database.conf

Default GitBucket database is in ~/.gitbucket/data

Try to connect by H2 Console.

**Comment by R3v1L** [comment]
Perfect. Now it works perfectly.

Thanks for taking your time to help me. :)

**Comment by hayasshi** [comment]
You're welcome!
I am also happy :)
